# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Publishing

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      machine:
        description: 'Machine to run on'     
        required: true
        default: 'macos-latest'

jobs:
  publish:
    env:
      LIBCLANG_DISABLE_CRASH_RECOVERY: 1
    strategy:
      matrix:
        os:
          - macos-latest
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - uses: eskatos/gradle-command-action@v1
      env:
        MAVEN_CENTRAL_PORTAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_PORTAL_USERNAME }}
        MAVEN_CENTRAL_PORTAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PORTAL_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        gradle-version: wrapper
        arguments: publish '-Pbinom.repo.url=${{ secrets.BINOM_REPO_URL }}' '-Pbinom.repo.user=${{ secrets.BINOM_REPO_USER }}' '-Pbinom.repo.password=${{ secrets.BINOM_REPO_PASSWORD }}' '-Pbinom.gpg.key_id=${{ secrets.GPG_KEY_ID }}' '-Pbinom.gpg.password=${{ secrets.GPG_PASSWORD }}' '-Pbinom.gpg.private_key=${{ secrets.GPG_PRIVATE_KEY }}'
#        arguments: publish '-Pbinom.repo.url=${{ secrets.BINOM_REPO_URL }}' '-Pbinom.repo.user=${{ secrets.BINOM_REPO_USER }}' '-Pbinom.repo.password=${{ secrets.BINOM_REPO_PASSWORD }}' '-Pbinom.gpg.key_id=${{ secrets.GPG_KEY_ID }}' '-Pbinom.gpg.password=${{ secrets.GPG_PASSWORD }}' '-Pbinom.gpg.private_key=${{ secrets.GPG_PRIVATE_KEY }}' '-Pbinom.central.username=${{ secrets.CENTRAL_USENAME }}' '-Pbinom.central.password=${{ secrets.CENTRAL_PASSWORD }}'
